;=============================================================================;
; string.inc - String utilities
; Author: Trevor Schiff
;=============================================================================;

;=============================================================================;
; Name: String_Length
;
; Details: Measures length of string
; 
; Arguments: pbMsg: String to measure
;
; Return: String length
;=============================================================================;
String_Length proto pbMsg: PTR BYTE
